### ISSUE TITLE
Design/Prep Database

### ISSUE THREAD

**Issue by VicaWorth** [VicaWorth/csci-36#6]
To allow for historic PLO storage.

**Comment by thatonekidgonzo** [comment]
DONE-
I added FK to DEP_ID in SUPER_PROGRAMS(should need one no?)
I made the tables we see in my sql blue. 
added PROG_UPDATE in table PROGRAMS to deal with the info of when slo was last updated
Cleaned lines a bit to connect to their respective keys for better readability
Update Bold unique values
Underline PK's
WANTS-
Still want to do some text saying what colors represent and what the dashed lines represent
Get clarification with luke on what dashed lines mean 
maybe make some sub-tables from the programs table since its impossible to read when you * ALL
Get some feedback on changes
put the type of relationship the tables have on the lines themselves 
GOAL-
To make it easier to edit by recreating in LucidChart
To start finding ways to optimize
Understand the database better and fully (Gonna ask Luke)
[PP.v2.pdf](https://github.com/VicaWorth/csci-36/files/9679282/PP.v2.pdf)
